---
- name: Container registry
  docker_container:
    name: registry
    state: started
    restart: yes
    image: registry:2
    volumes:
      -"{{ main_root }}/registry:/var/lib/registry"
    ports:
      - "5000:5000"

- name: pull an image
  docker_image:
    name: quay.io/coreos/etcd:v3.0.2      

- name: Tag and push to local registry
  docker_image:
     name: centos
     repository: localhost:5000/centos
     tag: 7
     push: yes


- name: Build an image and push it to a private repo
  docker_image:
    path: ./sinatra
    name: registry.ansible.com/chouseknecht/sinatra
    tag: v1
    push: yes
    
- name: Container etcd
  docker_container:
    name: etcd
    state: started
    restart: yes
    image: quay.io/coreos/etcd:v3.0.2
    ports:
      - "4002:4002"
    command: --listen-client-urls=http://0.0.0.0:4002 --advertise-client-urls=http://{{ ansible_default_ipv4.address }}:4002

- name: setup dns
  command: "curl -L -X PUT http://{{ ansible_default_ipv4.address }}:4002/v2/keys/skydns/config -d value=\"{\\\"dns_addr\\\":\\\"0.0.0.0:53\\\", \\\"ttl\\\":60, \\\"domain\\\": \\\"{{ domain_dns }}.\\\", \\\"nameservers\\\": [\\\"8.8.8.8:53\\\",\\\"8.8.4.4:53\\\"]}\""

- name: Container skydns
  docker_container:
    name: skydns
    state: started
    restart: yes
    image: skynetservices/skydns
    network_mode: host
    env:
      ETCD_MACHINES: http://{{ ansible_default_ipv4.address }}:4002

