- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add repository Docker
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker-ce
  yum:
    name: docker-ce
    state: latest

- name: Creates directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0700

- name: create daemon.json file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: dockerpath

- name: Clean docker path
  file:
    state: absent
    path: "{{ main_root }}/docker/"
  when: dockerpath.changed

- service:
    name: docker
    state: restarted
    enabled: true

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.14.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: install the latest version of python-pip
  yum:
    name: python-pip
    state: latest

- name: install the latest version of docker-pip
  pip:
    name: docker