---
- name: Container sync
  docker_container:
    name: sync
    state: started
    restart: no
    image: resilio/sync
    volumes:
      - "{{ main_root }}/btsync/:/mnt/sync"
    ports:
      - "8888:8888"          

- name: Container transmission
  docker_container:
    name: transmission
    state: started
    restart: no
    image: linuxserver/transmission
    volumes:
      - "{{ main_root }}/transmission/config:/config"
      - "{{ main_root }}/transmission/downloads:/downloads"
      - "{{ main_root }}/transmission/watch:/watch"
    ports:
      - "9091:9091"
      - "52413:52413"
      - "52413:51413/udp"
    env:
      TZ: Europe/London
      PGID: "{{ sharegid }}"
      PUID: "{{ shareuid }}"

- name: Container samba
  docker_container:
    name: samba
    state: started
    restart: no
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - "{{ samba_root }}:/Share"
      - "{{ main_root }}/Media:/Media"
      - "{{ main_root }}/transmission/:/Transmission"
    command: "-n -u \"{{ shareuser }};{{ sharepassword }}\" -s \"Share;/Share;yes;no;no;{{ shareuser }}\" -s \"Media;/Media;yes;no;no;{{ shareuser }}\" -s \"Transmission;/Transmission;yes;no;no;{{ shareuser }}\""        
    env:
      USERID: "{{ shareuid }}"
      GROUPID: "{{ sharegid }}"
      TZ: Europe/London

# - name: Container Plex
#   docker_container:
#     name: plex
#     state: started
#     restart: no
#     image: timhaak/plex
#     network_mode: host
#     volumes:
#       - "{{ main_root }}/Media:/data"
#       - "{{ main_root }}/plexConfig:/config"
#     env:
#       PLEX_EXTERNALPORT: 32400
#       PLEX_USERNAME: "{{ plex_user }}"
#       PLEX_PASSWORD: "{{ plex_password }}"
#       RUN_AS_ROOT: FALSE

#- iptables_raw:
#    name: allow_tcp_32400
#    rules: '-A INPUT -p tcp -m state --dport 32400 --state NEW,ESTABLISHED -j ACCEPT'

- name: Container Plex
  docker_container:
    name: plex
    state: started
    restart: no
    image: linuxserver/plex
    network_mode: host
    volumes:
      - "{{ main_root }}/Media:/data"
      - "{{ main_root }}/plexConfig:/config"
      - "{{ main_root }}/tmp:/transcode"
    env:
      PGID: "{{ sharegid }}"
      PUID: "{{ shareuid }}"
      TZ: Europe/London
      VERSION: latest

# - name: Container gitlab
#   docker_container:
#     name: gitlab
#     state: started
#     restart: yes
#     hostname: gitlab.cloud.local
#     image: gitlab/gitlab-ce:latest
#     ports:
#       #- "443:443"
#       - "8080:80"
#       - "2222:22"
#     volumes:
#       - "{{ main_root }}/gitlab/config:/etc/gitlab:Z"
#       - "{{ main_root }}/gitlab/logs:/var/log/gitlab:Z"
#       - "{{ main_root }}/gitlab/data:/var/opt/gitlab:Z"



# - name: Container etcd
#   docker_container:
#     name: etcd
#     state: started
#     restart: yes
#     image: quay.io/coreos/etcd:v3.0.2
#     ports:
#       - "4002:4002"
#     command: --listen-client-urls=http://0.0.0.0:4002 --advertise-client-urls=http://{{ ansible_default_ipv4.address }}:4002

# - name: setup dns
#   command: "curl -L -X PUT http://{{ ansible_default_ipv4.address }}:4002/v2/keys/skydns/config -d value=\"{\\\"dns_addr\\\":\\\"0.0.0.0:53\\\", \\\"ttl\\\":60, \\\"domain\\\": \\\"{{ domain_dns }}.\\\", \\\"nameservers\\\": [\\\"8.8.8.8:53\\\",\\\"8.8.4.4:53\\\"]}\""

# - name: Container skydns
#   docker_container:
#     name: skydns
#     state: started
#     restart: yes
#     image: skynetservices/skydns
#     network_mode: host
#     env:
#       ETCD_MACHINES: http://{{ ansible_default_ipv4.address }}:4002
