---
- hosts: cloud
  remote_user: root
  become: yes
  become_method: sudo

  pre_tasks:
    - name: create daemon.json file
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
  roles:
    - cloud
    - mongrelion.docker
    - docker_server